# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresspp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdata',
            name='mobileno',
            field=models.BigIntegerField(),
        ),
    ]
